CREATE DEFINER=`root`@`localhost` PROCEDURE `ADD_BOOK_TO_BOOKSHELF`(
IN BOOK_NAME VARCHAR (100),
IN USER_ID INT (50),
IN BOOKSHELF_ID INT (50),
IN CATEGORY VARCHAR (50)
)
BEGIN
DECLARE BOOK_ID INT;
DECLARE CATEGORY_ID INT;
SELECT B.ID INTO BOOK_ID FROM BOOK B WHERE B.TITLE = BOOK_NAME;
SELECT C.ID INTO CATEGORY_ID FROM CATEGORY C WHERE C.CATEGORY_TYPE = CATEGORY;


INSERT INTO BOOKSHELF (USER_ID, BOOK_ID, CATEGORY_ID, ADDED_DATE) VALUES (USER_ID, BOOK_ID, CATEGORY_ID, sysdate());
END