CREATE DEFINER=`root`@`localhost` PROCEDURE `FOLLOWING_REVIEWS`(IN FOLLOWER_ID INT, IN FOLLOWING_ID INT)
BEGIN
-- declare FOLLOWER_ID INT;
declare TEMP_COUNT INT;

SELECT count(*) INTO TEMP_COUNT FROM FOLLOW F WHERE F.FOLLOWER_USER_ID = FOLLOWER_ID AND F.FOLLOWING_USER_ID = FOLLOWING_ID;

IF TEMP_COUNT !=0 THEN 
SELECT U.FULL_NAME , B.TITLE, R.RATE, R.REVIEW_TEXT, R.REVIEW_DATE FROM REVIEW R 
JOIN USERS U ON R.USER_ID = U.ID
JOIN BOOK B ON R.BOOK_ID = B.ID
WHERE R.USER_ID = FOLLOWING_ID
;
-- ELSE select '' as message from dual;
END IF;
END