CREATE DEFINER=`root`@`localhost` PROCEDURE `JOIN_CLUB`(IN USER_ID INT, IN CLUB_NAME VARCHAR (50))
BEGIN
declare CLUB_DESCRIPTION VARCHAR (100);
SELECT C.DESCRIPTION INTO CLUB_DESCRIPTION FROM BOOK_CLUB C WHERE C.CLUB_NAME = CLUB_NAME;
INSERT INTO BOOK_CLUB (USER_ID, CLUB_NAME,DESCRIPTION, JOINED_DATE) VALUES (USER_ID, CLUB_NAME,CLUB_DESCRIPTION, sysdate());
END