CREATE DEFINER=`root`@`localhost` PROCEDURE `LIST_BOOK_BY_GENRE_AND_RATE`(IN GENRE_NAME VARCHAR (50), IN RATE INT)
BEGIN
SELECT B.TITLE, G.GENRE_NAME, A.AUTHOR_NAME, AG.AVG_RATE FROM BOOK B 
JOIN GENRE G ON B.GENRE_ID = G.ID
JOIN AVG_RATES AG ON B.ID = AG.BOOK_ID
JOIN AUTHOR A ON A.ID = B.AUTHOR_ID
WHERE G.GENRE_NAME = GENRE_NAME AND AG.AVG_RATE >= RATE;
END