CREATE DEFINER=`root`@`localhost` PROCEDURE `LIST_EMAILS_BY_LOGGIN`(IN LAST_LOGGIN DATE)
BEGIN
SELECT U.FULL_NAME, U.EMAIL, U.LAST_LOGIN, C.CATEGORY_TYPE FROM USERS U
JOIN BOOKSHELF BS ON U.ID = BS.USER_ID
JOIN CATEGORY C ON C.ID = BS.CATEGORY_ID
 JOIN BOOK B ON B.ID = BS.BOOK_ID
WHERE U.LAST_LOGIN <= LAST_LOGGIN;
END