CREATE DEFINER=`root`@`localhost` PROCEDURE `LIST_BOOK_BY_GENRE`(IN GENRE_NAME VARCHAR (50))
BEGIN
SELECT B.TITLE, B.RELEASED_DATE, G.GENRE_NAME , A.AUTHOR_NAME FROM BOOK B 
JOIN GENRE G ON B.GENRE_ID = G.ID 
JOIN AUTHOR A ON B.AUTHOR_ID = A.ID
WHERE G.GENRE_NAME = GENRE_NAME;
END