USE social_library;
DELIMITER //

CREATE DEFINER=`root`@`localhost`
 PROCEDURE `USER_REGISTRATION`(
    IN FULL_NAME VARCHAR(100),
    IN ADDRESS VARCHAR(100),
    IN EMAIL VARCHAR(50)
)
BEGIN
    INSERT INTO USERS (FULL_NAME,
    ADDRESS, EMAIL, 
    RIGESTERATION_DATE) VALUES 
    (FULL_NAME, ADDRESS, EMAIL, 
sysdate());
END //

DELIMITER ;
