CREATE DEFINER=`root`@`localhost` PROCEDURE `RECOMMEND_BOOKS`(IN USER_ID INT)
BEGIN
-- RECOMMEND BY READING_HISTORY
SELECT DISTINCT(B.TITLE), LRH.GENRE_NAME, LRH.AUTHOR_NAME, `RECOMMENDED BY YOUR READING HISTORY` FROM BOOK B
LEFT JOIN LIST_READING_HISTORY LRH ON B.GENRE_ID = LRH.GENRE_ID OR B.AUTHOR_ID = LRH.AUTHOR_ID
WHERE LRH.USER_ID = USER_ID

UNION ALL
SELECT  DISTINCT(B.TITLE), LUP.GENRE_NAME, LUP.AUTHOR_NAME, `RECOMMENDED BY YOUR PREFERENCES` FROM BOOK B
LEFT JOIN LIST_USERS_PREFERENCES LUP ON B.GENRE_ID = LUP.GENRE_ID OR B.AUTHOR_ID = LUP.AUTHOR_ID
WHERE LUP.USER_ID = USER_ID

UNION ALL
SELECT  DISTINCT(B.TITLE), LSRH.GENRE_FOR_FOLLOWING_USER AS GENRE_NAME, LSRH.BOOK_AUTHOR_FOR_FOLLOWING_USER AS AUTHOR_NAME, `RECOMMENDED BY OTHER USERS PREFERENCES` FROM BOOK B
LEFT JOIN LIST_SIMILAR_READING_HABITS LSRH ON B.GENRE_ID = LSRH.GENRE_ID OR B.AUTHOR_ID = LSRH.AUTHOR_ID
WHERE LSRH.USER_ID = USER_ID;
END