CREATE DEFINER=`root`@`localhost` PROCEDURE `SEARCH_BOOK`(IN BOOK_NAME VARCHAR (50))
BEGIN
SELECT B.TITLE, B.RELEASED_DATE, G.GENRE_NAME, A.AUTHOR_NAME FROM BOOK B
JOIN GENRE G ON B.GENRE_ID = G.ID
JOIN AUTHOR A ON B.AUTHOR_ID = A.ID
WHERE TITLE = BOOK_NAME;
END