CREATE DEFINER=`root`@`localhost` PROCEDURE `TAG_BOOK`(IN USER_ID INT, IN BOOK_NAME VARCHAR (50), 
IN TAG_NAME VARCHAR (50))
BEGIN
DECLARE BOOK_ID INT;
DECLARE GENRE_ID INT;
SELECT B.ID INTO BOOK_ID FROM BOOK B WHERE B.TITLE = BOOK_NAME;
SELECT G.ID INTO GENRE_ID FROM GENRE G JOIN BOOK B ON G.ID = B.GENRE_ID WHERE B.ID = BOOK_ID;

INSERT INTO TAG (USER_ID, BOOK_ID, GENRE_ID, TAG_NAME) VALUES (USER_ID, BOOK_ID, GENRE_ID, TAG_NAME);
END