CREATE DEFINER=`root`@`localhost` PROCEDURE `UPDATE_CATEGORY`(IN USER_ID INT, IN BOOK_NAME VARCHAR (50), IN NEW_CTAGORY VARCHAR (50))
BEGIN
DECLARE CATEGORY_ID INT;
DECLARE BOOK_ID INT;
DECLARE RECORD_EXISTS INT;
SELECT C.ID INTO CATEGORY_ID FROM CATEGORY C WHERE C.CATEGORY_TYPE = NEW_CTAGORY;
SELECT B.ID INTO BOOK_ID FROM BOOK B WHERE B.TITLE = BOOK_NAME;

SELECT COUNT(*) INTO RECORD_EXISTS FROM BOOKSHELF BS WHERE BS.USER_ID = USER_ID AND BS.BOOK_ID = BOOK_ID;

IF RECORD_EXISTS = 0 THEN
SIGNAL SQLSTATE '45000'
SET MESSAGE_TEXT = 'This book is not in your bookshelf';

ELSE
UPDATE BOOKSHELF BS
SET BS.CATEGORY_ID = CATEGORY_ID 
WHERE BS.USER_ID = USER_ID AND BS.BOOK_ID = BOOK_ID;
END IF;
END