CREATE DEFINER=`root`@`localhost` PROCEDURE `WRITE_REVIEW`(IN USER_ID INT, IN BOOK_NAME VARCHAR (50), IN RATE INT, IN REVIEW_TEXT VARCHAR (250))
BEGIN
declare BOOK_ID INT;
SELECT B.ID INTO BOOK_ID FROM BOOK B WHERE B.TITLE = BOOK_NAME;

INSERT INTO REVIEW (USER_ID, BOOK_ID, RATE, REVIEW_TEXT, REVIEW_DATE) VALUES (USER_ID, BOOK_ID, RATE, REVIEW_TEXT, sysdate());
END