
DROP TRIGGER CHECK_BEFORE_REVIEW;
DELIMITER //

CREATE TRIGGER CHECK_BEFORE_REVIEW
BEFORE INSERT ON REVIEW 
FOR EACH ROW
BEGIN
DECLARE REVIEW_EXISTS INT;
DECLARE CATEGORY_ID INT;

SELECT COUNT(*) INTO REVIEW_EXISTS FROM REVIEW R
JOIN BOOKSHELF BS ON BS.BOOK_ID = R.BOOK_ID
WHERE R.USER_ID = NEW.USER_ID AND R.BOOK_ID = NEW.BOOK_ID;

IF REVIEW_EXISTS != 0 THEN
SIGNAL SQLSTATE '45000'
SET MESSAGE_TEXT = 'Cannot review a book that you have reviewed ir before';
END IF;


SELECT BS.CATEGORY_ID INTO CATEGORY_ID FROM BOOKSHELF BS 
JOIN CATEGORY C ON C.ID = BS.CATEGORY_ID
WHERE BS.USER_ID = NEW.USER_ID;

IF CATEGORY_ID != 1 THEN
SIGNAL SQLSTATE '45000'
SET MESSAGE_TEXT = 'Cannot review a book that you have not read ir before';
END IF;

END//

DELIMITER ;