
 USE SOCIAL_LIBRARY;

DROP TRIGGER CHECK_BEFORE_ADD_TO_BOOKSHELF;
DELIMITER //

CREATE TRIGGER CHECK_BEFORE_ADD_TO_BOOKSHELF
BEFORE INSERT ON BOOKSHELF 
FOR EACH ROW
BEGIN
DECLARE USER_EXISTS INT;

SELECT COUNT(*) INTO USER_EXISTS FROM BOOKSHELF BS
WHERE BS.USER_ID = NEW.USER_ID AND BS.BOOK_ID = NEW.BOOK_ID;

IF USER_EXISTS = 1 THEN
SIGNAL SQLSTATE '45000'
SET MESSAGE_TEXT = 'This book is already exists in your bookshelf';
END IF;
END//

DELIMITER ;