DROP TRIGGER CHECK_BEFORE_FOLLOW;
DELIMITER //

CREATE TRIGGER CHECK_BEFORE_FOLLOW
BEFORE INSERT ON FOLLOW 
FOR EACH ROW
BEGIN
DECLARE FOLLOWERS_EXISTS INT;
DECLARE FOLLOWING_USER_EXISTS INT;
DECLARE FOLLOWER_USER_EXISTS INT;

SELECT COUNT(*) INTO 
FOLLOWERS_EXISTS FROM FOLLOW F
WHERE F.FOLLOWER_USER_ID = NEW.FOLLOWER_USER_ID 
AND F.FOLLOWING_USER_ID = NEW.FOLLOWING_USER_ID ;

IF FOLLOWERS_EXISTS = 1 THEN
SIGNAL SQLSTATE '45000'
SET MESSAGE_TEXT = 
'YOU ALREADY FOLLOW THIS USER';
END IF;

SELECT COUNT(*) INTO FOLLOWING_USER_EXISTS FROM USERS U
WHERE U.ID = NEW.FOLLOWING_USER_ID;

IF FOLLOWING_USER_EXISTS = 0 THEN
SIGNAL SQLSTATE '45000'
SET MESSAGE_TEXT = 
'THE FOLLOWING USER NOT EXISTS';
END IF;


SELECT COUNT(*) INTO FOLLOWER_USER_EXISTS FROM USERS U
WHERE U.ID = NEW.FOLLOWER_USER_ID;

IF FOLLOWER_USER_EXISTS = 0 THEN
SIGNAL SQLSTATE '45000'
SET MESSAGE_TEXT = 
'THE FOLLOWER USER NOT EXISTS';
END IF;



IF NEW.FOLLOWER_USER_ID = NEW.FOLLOWING_USER_ID THEN
SIGNAL SQLSTATE '45000'
SET MESSAGE_TEXT = 
'ERROR';
END IF;
END//

DELIMITER ;